services:
  open-api-mcp:
    image: open-api-mcp
    container_name: open-api-mcp
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    environment:
      - OPEN_API_FILE=/app/open-api.json
      - API_URL=https://fakestoreapi.com
      # - API_KEY
      # - MCP_NAME=My MCP Server
      # - MCP_VERSION=1.0.0
      # - MCP_TRANSPORT_TYPE=sse|stdio

 