services:
  open-api-mcp:
    image: nexpando/open-api-mcp
    container_name: open-api-mcp
    ports:
      - "3000:3000"
    volumes:
    - type: bind
      source: ./open-api.json
      target: /app/open-api.json
    environment:
      - OPEN_API_FILE=/app/open-api.json
      - API_URL=  #Example: https://fakestoreapi.com
      # - API_KEY
      # - MCP_NAME=My MCP Server
      # - MCP_VERSION=1.0.0
      # - MCP_TRANSPORT_TYPE=sse|stdio
