services:
  mailgun-mcp:
    image: nexpando/open-api-mcp
    container_name: mailgun-mcp
    ports:
      - "3000:3000"
    volumes:
    - type: bind
      source: ./get-axios.ts
      target: /app/get-axios.ts
    - ./specs:/app/specs
    environment:
      - OPEN_API_FILE=/app/specs/open-api.yml
      - API_URL=https://api.mailgun.net
      - API_KEY=secret
      - MCP_NAME=Mailgun MCP
      - MCP_VERSION=0.0.1